const initialEdges = [
    {
      id: 'e1-2',
      source: '1',
      type: 'step',
      target: '2',
      sourceHandle: 'method',  
      targetHandle: 'method', 
      animated: false,  
      arrowHeadType: 'arrow',
      style: { stroke: '#fff', strokeWidth: 2 },
      markerEnd: {
          type: 'arrowclosed', 
          color: '#fff',
          width: 10,
          height: 10,
        },
    },
    {
      id: 'e1-2',
      source: '1',
      sourceHandle: 'method',  
      target: '3',
      type: 'step',
      targetHandle: 'method', 
      animated: false,  
      arrowHeadType: 'arrow',
      style: { stroke: '#fff', strokeWidth: 2 },
      markerEnd: {
          type: 'arrowclosed', 
          color: '#fff',
          width: 10,
          height: 10,
        },
    },
    {
        id: 'e1-2',
        source: '2',
        sourceHandle: 'method',  
        target: '4',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '2',
        sourceHandle: 'method',  
        target: '5',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '2',
        sourceHandle: 'method',  
        target: '6',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '6',
        sourceHandle: 'method',  
        target: '2',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '3',
        sourceHandle: 'method',  
        target: '7',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '3',
        sourceHandle: 'method',  
        target: '8',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
      {
        id: 'e1-2',
        source: '3',
        sourceHandle: 'method',  
        target: '9',
        type: 'step',
        targetHandle: 'method',  
        animated: false,  
        arrowHeadType: 'arrow',
        style: { stroke: '#fff', strokeWidth: 2 },
        markerEnd: {
            type: 'arrowclosed', 
            color: '#fff',
            width: 10,
            height: 10,
          },
      },
  ];

  export default initialEdges;